version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: reinventar_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-reinventar_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reinventar_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      # Variáveis de ambiente passadas do .env para o container
      DB_HOST: postgres # Nome do serviço do banco de dados no docker-compose
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-reinventar_db}
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      # Adicionar outras variáveis do .env.example aqui

volumes:
  postgres_data:
